### ISSUE TITLE
cannot find any candidates?

### ISSUE THREAD

**Issue by Jiangjao** [aehrc/isling#1]
Removing temporary output file /biosoft/isling/out/pipeline-test/test-merge/host_aligned/E1            00007032_L01_639.host.readsFromFHV.bam.
[Thu Aug  5 16:46:02 2021]
Finished job 26.
42 of 54 steps (78%) done
Select jobs to execute...

[Thu Aug  5 16:46:02 2021]
rule find_ints:
    input: /biosoft/isling/out/pipeline-test/test-merge/host_aligned/E100007032_L01_639.0.h            ost.readsFromFHV.bam, /biosoft/isling/out/pipeline-test/test-merge/virus_aligned/E100007032            _L01_639.0.FHV.bam, /biosoft/isling/out/pipeline-test/test-merge/host_stats/E100007032_L01_            639.host.readsFromFHV.txt, /biosoft/isling/out/pipeline-test/test-merge/virus_stats/E100007            032_L01_639.FHV.txt
    output: /biosoft/isling/out/pipeline-test/test-merge/ints/E100007032_L01_639.0.host.FHV            .txt
    jobid: 9
    wildcards: outpath=/biosoft/isling/out/pipeline-test, dset=test-merge, samp=E100007032_            L01_639, part=0, host=host, virus=FHV
    resources: tmpdir=/tmp, mem_mb=100, time=30, nodes=1

**_using mean fragment length 0_**
[E::idx_find_and_load] Could not retrieve index file for '/biosoft/isling/out/pipeline-test            /test-merge/host_aligned/E100007032_L01_639.0.host.readsFromFHV.bam'
[E::idx_find_and_load] Could not retrieve index file for '/biosoft/isling/out/pipeline-test            /test-merge/virus_aligned/E100007032_L01_639.0.FHV.bam'
warning: insert size is zero - the position for discordant integration sites will be at the end of the mapped read
Traceback (most recent call last):
  File "/biosoft/isling/scripts/find_ints.py", line 3459, in <module>
    main()
  File "/biosoft/isling/scripts/find_ints.py", line 40, in main
    pair.find_integrations()
  File "/biosoft/isling/scripts/find_ints.py", line 90, in find_integrations
    for _ in self._get_aligns():
  File "/biosoft/isling/scripts/find_ints.py", line 269, in _get_aligns
    self.curr_host = self.host.collect_next_read_alignments()
  File "/biosoft/isling/scripts/find_ints.py", line 406, in collect_next_read_alignments
    query_name = self.curr.query_name
AttributeError: 'NoneType' object has no attribute **_'query_name'_**
[Thu Aug  5 16:46:02 2021]
Error in rule find_ints:
    jobid: 9
    output: /biosoft/isling/out/pipeline-test/test-merge/ints/E100007032_L01_639.0.host.FHV            .txt
    shell:

                if [ 'estimate' = 'estimate' ]; then
                        HOST=$(perl -ne '/^SN\sinsert size average:     (\d+\.\d+)/ && print "$1"' /share/home/stu_j            iangjiao/biosoft/isling/out/pipeline-test/test-merge/host_stats/E100007032_L01_639.host.readsFromFHV.txt)
                        VIRUS=$(perl -ne '/^SN\sinsert size average:    (\d+\.\d+)/ && print "$1"' /share/home/stu_j            iangjiao/biosoft/isling/out/pipeline-test/test-merge/virus_stats/E100007032_L01_639.FHV.txt)
                        FRAG=$(echo $HOST $VIRUS | awk '{print ($1 + $2) / 2}')
                else
                        FRAG=estimate
                fi

                echo "using mean fragment length $FRAG"

                python3 scripts/find_ints.py            --host /biosoft/isling/out/pipeline            -test/test-merge/host_aligned/E100007032_L01_639.0.host.readsFromFHV.bam                --virus /share/home/stu_jian            gjiao/biosoft/isling/out/pipeline-test/test-merge/virus_aligned/E100007032_L01_639.0.FHV.bam            --mean-templ            ate-length $FRAG                --integrations /biosoft/isling/out/pipeline-test/test-merge            /ints/E100007032_L01_639.0.host.FHV.txt --map-thresh 20 --tolerance 3 --nm-pc 0.6 --nm-diff 2

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by szsctt** [comment]
Thanks for the bug report!  Firstly, did the test data included with isling run ok?  I'm assuming this is the case, and this bug only appears with your own data.  

This could be because one of the input alignment files for this step was empty or didn't contain any reads that match the other alignment file.  This could happen if there aren't actually any integrations in the data.  Is this data where you actually expect to see integrations?

I've pushed a potential fix is this is the issue, but you can also check the alignments using:
```
grep ^SN /biosoft/isling/out/pipeline-test/test-merge/host_stats/E100007032_L01_639.host.readsFromFHV.txt | cut -f 2-
grep ^SN biosoft/isling/out/pipeline-test/test-merge/virus_stats/E100007032_L01_639.FHV.txt | cut -f 2-
```

If you have few alignments in the host alignment, this is likely the cause.

You can also check out the bam files (I typically use IGV) to see if you can manually spot any chimeric reads.

**Comment by Jiangjao** [comment]
yeah, I use my the data of  our biocamp.Thank you.

**Comment by Jiangjao** [comment]
### e,how to deal with Column `X1` doesn't exist.


Paramter 'merge-dist' not specified for dataset test-merge: using default 100
Paramter 'bed-include' not specified for dataset test-merge: using default []
Paramter 'generate-report' not specified for dataset test-merge: using default True
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 30
Rules claiming more threads will be scaled down.
Conda environments: ignored
Singularity containers: ignored
Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
rmd_summary_dataset        1              1              1
total                      2              1              1

Select jobs to execute...

[Sat Sep  4 12:22:43 2021]
rule rmd_summary_dataset:
    input: /share/home/biosoft/isling-master/out/pipeline-test/test-merge/ints/E100007032_L01_639.host.FHV.integrations.post.unique.txt, /share/home/biosoft/isling-master/out/pipeline-test/test-merge/ints/E100007032_L01_639.host.FHV.integrations.post.host_ambig.txt, /share/home/biosoft/isling-master/out/pipeline-test/test-merge/ints/E100007032_L01_639.host.FHV.integrations.post.virus_ambig.txt, /share/home/biosoft/isling-master/out/pipeline-test/summary/test-merge.analysis_conditions.tsv, /share/home/biosoft/isling-master/out/pipeline-test/references/host/host.ann, /share/home/biosoft/isling-master/out/pipeline-test/references/FHV/FHV.ann
    output: /share/home/biosoft/isling-master/out/pipeline-test/summary/test-merge.html
    jobid: 2
    wildcards: outpath=/share/home/biosoft/isling-master/out/pipeline-test, dset=test-merge
    resources: tmpdir=/tmp, mem_mb=1000, time=30



processing file: summary.Rmd
  |...                                                                   |   4%
  ordinary text without R code

  |......                                                                |   8%
label: setup (with options)
List of 1
 $ include: logi FALSE

  |........                                                              |  12%
   inline R code fragments

  |...........                                                           |  16%
label: analysisConditions
New names:
* `` -> ...1
Rows: 1 Columns: 37
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (22): dataset, config_dataset, sample, host, host_fasta, host_prefix, vi...
dbl (14): ...1, merge, trim, dedup, merge_n_min, clip_cutoff, cigar_tol, spl...
lgl  (1): bam_file

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Quitting from lines 40-72 (summary.Rmd)
**_Error: Can't subset columns that don't exist._**
✖ Column `X1` doesn't exist.
Backtrace:
     █
  1. ├─rmarkdown::render("scripts/summary.Rmd", output_file = "/share/home/biosoft/isling-master/out/pipeline-test/summary/test-merge.html")
  2. │ └─knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. │   └─knitr:::process_file(text, output)
  4. │     ├─base::withCallingHandlers(...)
  5. │     ├─knitr:::process_group(group)
  6. │     └─knitr:::process_group.block(group)
  7. │       └─knitr:::call_block(x)
  8. │         └─knitr:::block_exec(params)
  9. │           └─knitr:::eng_r(options)
 10. │             ├─knitr:::in_dir(...)
 11. │             └─knitr:::evaluate(...)
 12. │               └─evaluate::evaluate(...)
 13. │                 └─evaluate:::evaluate_call(...)
 14. │                   ├─evaluate:::timing_fn(...)
 15. │                   ├─base:::handle(...)
 16. │                   ├─base::withCallingHandlers(...)
 17. │                   ├─base::withVisible(eval(expr, envir, enclos))
 18. │                   └─base::eval(expr, envir, enclos)
 19. │                     └─base::eval(expr, envir, enclos)
 20. ├─readr::read_tsv(conditions_file) %>% dplyr::select(-X1) %>% dplyr::select(-config_dataset)
 21. ├─dplyr::select(., -config_dataset)
 22. ├─dplyr::select(., -X1)
 23. └─dplyr:::select.data.frame(., -X1)
 24.   └─tidyselect::eval_select(expr(c(...)), .data)
 25.     └─tidyselect:::eval_select_impl(...)
 26.       ├─tidyselect:::with_subscript_errors(...)
 27.       │ ├─base::tryCatch(...)
 28.       │ │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
 29.       │ │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 30.       │ │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
 31.       │ └─tidyselect:::instrument_base_errors(expr)
 32.       │   └─base::withCallingHandlers(...)
 33.       └─tidyselect:::vars_select_eval(...)
 34.         └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 35.           └─tidyselect:::eval_c(expr, data_mask, context_mask)
 36.             └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 37.               └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 38.                 └─tidyselect:::as_indices_sel_impl(...)
 39.                   └─tidyselect:::as_indices_impl(x, vars, strict = strict)
 40.                     └─tidyselect:::chr_as_locations(x, vars)
 41.                       └─vctrs::vec_as_location(x, n = length(vars), names = vars)
 42.                         └─(function () ...
 43.                           └─vctrs:::stop_subscript_oob(...)
 44.                             └─vctrs:::stop_subscript(...)

Execution halted
[Sat Sep  4 12:22:48 2021]
Error in rule rmd_summary_dataset:
    jobid: 2
    output: /share/home/biosoft/isling-master/out/pipeline-test/summary/test-merge.html
    shell:

                Rscript -e 'params=list("outdir"="/share/home/biosoft/isling-master/out/pipeline-test", "host"="host", "virus"="FHV", "dataset"="test-merge"); rmarkdown::render("scripts/summary.Rmd", output_file="/share/home/biosoft/isling-master/out/pipeline-test/summary/test-merge.html")'

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /share/home/biosoft/isling-master/.snakemake/log/2021-09-04T122239.667453.snakemake.log

**Comment by szsctt** [comment]
This is an issue in the Rmarkdown reports for the detected integration sites.  These still might have some bugs - I haven't had  a chance to look at them yet.  If you just want to know if you have some integrations, you can skip these steps by adding 'generate-report: False' to your config file.
