### ISSUE TITLE
mem_mb for Clumpify rule

### ISSUE THREAD

**Issue by szsctt** [aehrc/isling#6]
Clumpify seems to sometimes use a ton of memory (usually I use subs=2).  For example, when I have input files like so:

```
-r--r--r-- 1 sco305 hpc-users 1.6G Sep  9 14:33 /scratch1/sco305/intvi_cmri/data/reads/AGRF_CAGRF20083481_JBH4G/21F_B_1in20_JBH4G_ATCCAGAG-CGACGTTA_L001_R2.fastq.gz
-r--r--r-- 1 sco305 hpc-users 1.4G Sep  9 14:33 /scratch1/sco305/intvi_cmri/data/reads/AGRF_CAGRF20083481_JBH4G/21F_B_1in20_JBH4G_ATCCAGAG-CGACGTTA_L001_R1.fastq.gz
```

And I run the clumpify rule on a cluster, and use `sacct` to check how the job went, I see this:

```
       JobID    JobName  Partition      User  AllocCPUS   NNodes    Elapsed   TotalCPU      State  MaxVMSize     MaxRSS     ReqMem        NodeList 
------------ ---------- ---------- --------- ---------- -------- ---------- ---------- ---------- ---------- ---------- ---------- --------------- 
56175482     snakejob.+         h2    sco305          1        1   00:30:23  28:43.027    TIMEOUT                          30968Mn            c204 
56175482.ba+      batch                               1        1   00:30:26  28:43.027  CANCELLED  33022032K  18715348K    30968Mn            c204 
```

This particular job didn't even finish, but it's already had a MaxVMSize of ~33GB, and MaxRSS of ~18GB.

Sometimes I also see errors in the clumpify rule like so:
```
Activating singularity image /scratch1/sco305/intvi_cmri/tools_align/.snakemake/singularity/8c5d4fe7802fb686d4db98d5a5773fce.simg
java -ea -Xmx21912m -Xms21912m -cp /opt/conda/opt/bbmap-38.86-0/current/ clump.Clumpify -Xmx21912m in1=/scratch1/sco305/intvi_cmri/data/reads/AGRF_CAGRF20083481_JBH4G/6M_A_1in5_JBH4G_CGGCTAAT-AGAACGAG_L001_R1.fastq.gz in2=/scratch1/sco305/intvi_cmri/data/reads/AGRF_CAGRF20083481_JBH4G/6M_A_1in5_JBH4G_CGGCTAAT-AGAACGAG_L001_R2.fastq.gz out1=/scratch2/sco305/intvi_cmri/out_align/AGRF_CAGRF20083481_JBH4G/dedup_reads/6M_A_1in5_JBH4G_CGGCTAAT-AGAACGAG.1.fastq.gz out2=/scratch2/sco305/intvi_cmri/out_align/AGRF_CAGRF20083481_JBH4G/dedup_reads/6M_A_1in5_JBH4G_CGGCTAAT-AGAACGAG.2.fastq.gz dedupe=t ac=f subs=2 threads=1
Executing clump.Clumpify [-Xmx21912m, in1=/scratch1/sco305/intvi_cmri/data/reads/AGRF_CAGRF20083481_JBH4G/6M_A_1in5_JBH4G_CGGCTAAT-AGAACGAG_L001_R1.fastq.gz, in2=/scratch1/sco305/intvi_cmri/data/reads/AGRF_CAGRF20083481_JBH4G/6M_A_1in5_JBH4G_CGGCTAAT-AGAACGAG_L001_R2.fastq.gz, out1=/scratch2/sco305/intvi_cmri/out_align/AGRF_CAGRF20083481_JBH4G/dedup_reads/6M_A_1in5_JBH4G_CGGCTAAT-AGAACGAG.1.fastq.gz, out2=/scratch2/sco305/intvi_cmri/out_align/AGRF_CAGRF20083481_JBH4G/dedup_reads/6M_A_1in5_JBH4G_CGGCTAAT-AGAACGAG.2.fastq.gz, dedupe=t, ac=f, subs=2, threads=1]
Version 38.86

java.lang.Exception: 
Mismatch between length of bases and qualities for read 1010 (id=M00859:339:000000000-JBH4G:1:1101:10421:3670 1:N:0:CGGCTAAT+AGAACGAG).
# qualities=223, # bases=300

CCCCCGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGEGGFDDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG8FGGGGGGGGGGGGGGGGGGGGGGGGGGGGG@FFGGGCFFFGGGEGGGGGGGGGGFGGGGGGGGGGGGFGGGGGGGGCGGGGFGFCFGG+2@FFEEGCCFGEGGGG9++5<CEG
AAATTAGCCGGGTGTGGTGGCAGGCGCCTGTAGTCCCAGCTACTCAGGAGGCTGAGGCAGGAGAATTGCTTGAACCTAGGAGGCGGAGGTTGCAGTGAGCAGAGATCGCTCCATTGCACTCCAGCCTGGGCGACGAGCGAAACTCCAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGGCTAATTCTTCTGCCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAACACTATACTGACAACTTATTCACAACGACATCGAGAGCTATGCTGTATGGTTTTGTGGCCTGCGGGT

This can be bypassed with the flag 'tossbrokenreads' or 'nullifybrokenquality'
	at shared.KillSwitch.kill(KillSwitch.java:96)
	at stream.Read.validateQualityLength(Read.java:216)
	at stream.Read.validate(Read.java:104)
	at stream.Read.<init>(Read.java:76)
	at stream.Read.<init>(Read.java:50)
	at stream.FASTQ.quadToRead_slow(FASTQ.java:824)
	at stream.FASTQ.toReadList(FASTQ.java:659)
	at stream.FastqReadInputStream.fillBuffer(FastqReadInputStream.java:107)
	at stream.FastqReadInputStream.hasMore(FastqReadInputStream.java:73)
	at stream.ConcurrentGenericReadInputStream$ReadThread.readLists(ConcurrentGenericReadInputStream.java:667)
	at stream.ConcurrentGenericReadInputStream$ReadThread.run(ConcurrentGenericReadInputStream.java:656)
```

However, when I check the sequence and quality of the read in question, they're the same length. I assume this is a memory-related issue.

I've yet to work out how to work out the best way to calculate how much memory to give these jobs. I suppose it depends on the size of the input files and the number of substitutions?

**Comment by szsctt** [comment]
I can't think of a reason that it would be specific to the cluster, except that on the cluster memory usage is enforced. If you run everything on one machine it's not (unless you use all of the memory of that machine), so if the jobs aren't all running at the same time then maybe you just get away with it?  Have you checked to see how much memory these jobs use in your case?

**Comment by szsctt** [comment]
Perhaps it could be related to this: https://www.mail-archive.com/slurm-dev@schedmd.com/msg09340.html
But in this case I'm only using one thread for Clumpify so it's probably not exactly the same issue
